server:
  port: ${PORT:8081}
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: ${SPRING_APPLICATION_NAME:microservice-baseproject-expense}
  # zipkin
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}
    enabled: true
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:baseapiexpense}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  # Flyway
  flyway:
    enabled: true
  # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: update
management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: 'true'
    defaults:
      enabled: 'true'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    
app-config:
  rabbit:
    queue:
      person-create: person-create.queue
      person-update: person-update.queue
      person-delete: person-delete.queue
      start: start.queue

