version: "3"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - baseproject-network
    ports:
      - 9411:9411

  baseproject-db:
    image: postgres:11
    container_name: baseproject-db
    restart: always
    networks:
      - baseproject-network
    environment:
      - POSTGRES_DB=baseproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5433:5432

  baseproject-api:
    build: "./baseproject"
    container_name: baseproject
    depends_on:
      - baseproject-db
      - zipkin
    networks:
      - baseproject-network
    environment:
      - PORT=8080
      - SPRING_APPLICATION_NAME=microservice-baseproject
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
      - DB_HOST=baseproject-db
      - DB_NAME=baseproject
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
    ports:
      - 8080:8080

  baseproject-web:
    container_name: baseprojectweb
    depends_on:
      - baseproject-api
    networks:
      - baseproject-network
    build: "./baseprojectweb"
    ports:
      - "4200:4200"

networks:
  baseproject-network:
    driver: bridge
