server:
  port: 8087

spring:
  application:
    name: api-gateway

  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: microservice-baseproject
          uri: lb://MICROSERVICE-BASEPROJECT
          predicates:
            - Path=/api/expense-controls/**, /api/enums/**, /api/persons/**, /api/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    enabled: true
